name: Java and Vue CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.1.0'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew buildWithFrontend

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build/libs/*.jar



      # Configuração do SSH Agent para usar a chave SSH privada com senha
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}  # Adicione esta linha com a senha

      # Copiar o arquivo JAR para o servidor usando SCP
      - name: Copy JAR to Server
        run: scp build/libs/*.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/saudeemequilibrio/
