name: Java and Vue CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.1.0'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('*/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      - name: Build with Gradle
        run: ./gradlew buildWithFrontend


      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build/libs/*.jar


      - name: Copy JAR to Workspace Root
        run: cp build/libs/*.jar ./



      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}






      - name: Remove Old JAR Files
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -f /home/saudeemequilibrio/microbiome-lab-ufu-0.0.1-SNAPSHOT.jar




      - name: Copy New JAR to Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './*.jar'
          target: '/home/saudeemequilibrio/'



      - name: Start New Application
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/saudeemequilibrio/
            tmux new-session -d -s myapp 'java -Dspring.profiles.active=prod -jar microbiome-lab-ufu-0.0.1-SNAPSHOT.jar'




      - name: Remove JAR from Workspace
        run: rm ./*.jar